#!/bin/sh

run_install()
{
	apt-get install ${dependencies[@]}
}
dependencies=("openssl" "git" "python3" "python3-pyqt5")

dpkg -s "{$dependencies[@]}" >/dev/null 2>&1 || run_install

git clone https://github.com/KieferSivitz/secretChat.git
cd secretChat

echo "Generating SSL Certificate"
echo " "
openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
openssl rsa -passin pass:x -in server.pass.key -out server.key
rm server.pass.key

echo " "
echo "These questions are not very important, as we are using the cert to encrypt but not authenticate"
echo " "
openssl req -new -key server.key -out server.csr
openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt

rm setup

echo "All done! type 'cd secretChat' to move into the folder with our program"
echo "Execute 'python3 secretChat.py' to run the program!"
